"""
Rule version history.

Records the version, id, and source file of every YAML rule each time
the loader registers rules into an engine. Only writes when a rule's
version differs from the most recently recorded version, so repeat
reloads of an unchanged rules directory do not produce rows.

The table is created on first use if it does not already exist. Both
SQLite and PostgreSQL schemas are supported. No third-party deps.
"""
from __future__ import annotations
# KAVACH360-patch-10b-versions-applied
import threading
import time
from typing import Any, Dict, List

_TABLE_DDL = {
    "sqlite": (
        "CREATE TABLE IF NOT EXISTS detection_rule_versions ("
        "  seq INTEGER PRIMARY KEY AUTOINCREMENT,"
        "  ts TEXT NOT NULL,"
        "  rule_id TEXT NOT NULL,"
        "  version INTEGER NOT NULL,"
        "  source_file TEXT NOT NULL,"
        "  enabled INTEGER NOT NULL,"
        "  actor TEXT)"
    ),
    "postgres": (
        "CREATE TABLE IF NOT EXISTS detection_rule_versions ("
        "  seq BIGSERIAL PRIMARY KEY,"
        "  ts TIMESTAMPTZ NOT NULL,"
        "  rule_id TEXT NOT NULL,"
        "  version INTEGER NOT NULL,"
        "  source_file TEXT NOT NULL,"
        "  enabled INTEGER NOT NULL,"
        "  actor TEXT)"
    ),
}

_INDEX_DDL = (
    "CREATE INDEX IF NOT EXISTS idx_drv_rule_id "
    "ON detection_rule_versions(rule_id, seq DESC)"
)


def _backend_kind(db) -> str:
    """Return 'sqlite' or 'postgres' from the storage object."""
    # Prefer an explicit attribute if the backend exposes one.
    ph = getattr(db, "placeholders", "?")
    if ph == "%s":
        return "postgres"
    return "sqlite"


class RuleVersionStore:
    """Thin wrapper that records rule version changes.

    Table creation is per-instance via CREATE TABLE IF NOT EXISTS.
    No class-level cache: a store bound to a new database must
    ensure the table exists in that database.
    """

    def __init__(self, db) -> None:
        self.db = db
        self._table_ready = False
        self._ensure_lock = threading.Lock()
        self._maybe_create_table()

    def _maybe_create_table(self) -> None:
        if self._table_ready:
            return
        with self._ensure_lock:
            if self._table_ready:
                return
            kind = _backend_kind(self.db)
            ddl = _TABLE_DDL[kind]
            with self.db.tx() as c:
                cur = c.cursor() if hasattr(c, "cursor") else c
                if hasattr(self.db, "adapt"):
                    cur.execute(self.db.adapt(ddl))
                    cur.execute(self.db.adapt(_INDEX_DDL))
                else:
                    cur.execute(ddl)
                    cur.execute(_INDEX_DDL)
            self._table_ready = True

    def _latest_versions(self) -> Dict[str, int]:
        try:
            rows = self.db.query(
                "SELECT rule_id, MAX(version) AS v "
                "FROM detection_rule_versions GROUP BY rule_id")
        except Exception:
            return {}
        out: Dict[str, int] = {}
        for r in rows:
            try:
                out[r["rule_id"]] = int(r["v"])
            except Exception:
                continue
        return out

    def record(self, loaded_rules: List[Any], actor: str = "reload") -> int:
        """
        Record version rows for rules whose version differs from the
        latest recorded version for that rule id. Returns the number of
        rows written.

        `loaded_rules` items must expose .rule_id, .version,
        .source_file, .enabled attributes (YamlRule satisfies this).
        """
        latest = self._latest_versions()
        to_write = []
        now = None
        for r in loaded_rules:
            rid = getattr(r, "rule_id", None)
            ver = getattr(r, "version", None)
            if not rid or ver is None:
                continue
            if latest.get(rid) == int(ver):
                continue
            to_write.append((rid, int(ver),
                             getattr(r, "source_file", ""),
                             1 if getattr(r, "enabled", True) else 0))
        if not to_write:
            return 0
        # Use a timestamp generated by the DB dialect. SQLite uses
        # datetime('now'), PostgreSQL uses NOW().
        kind = _backend_kind(self.db)
        try:
            with self.db.tx() as c:
                cur = c.cursor() if hasattr(c, "cursor") else c
                for rid, ver, path, enabled in to_write:
                    if kind == "postgres":
                        sql = ("INSERT INTO detection_rule_versions"
                               "(ts,rule_id,version,source_file,enabled,actor) "
                               "VALUES(NOW(),?,?,?,?,?)")
                    else:
                        sql = ("INSERT INTO detection_rule_versions"
                               "(ts,rule_id,version,source_file,enabled,actor) "
                               "VALUES(datetime('now'),?,?,?,?,?)")
                    if hasattr(self.db, "adapt"):
                        sql = self.db.adapt(sql)
                    cur.execute(sql, (rid, ver, path, enabled, actor))
        except Exception:
            # Version history is best-effort; a failure here must not
            # abort the reload.
            return 0
        return len(to_write)

    def list(self, rule_id: str = None, limit: int = 200) -> List[Dict[str, Any]]:
        try:
            if rule_id:
                rows = self.db.query(
                    "SELECT seq, ts, rule_id, version, source_file, enabled, actor "
                    "FROM detection_rule_versions WHERE rule_id=? "
                    "ORDER BY seq DESC LIMIT ?", (rule_id, int(limit)))
            else:
                rows = self.db.query(
                    "SELECT seq, ts, rule_id, version, source_file, enabled, actor "
                    "FROM detection_rule_versions ORDER BY seq DESC LIMIT ?",
                    (int(limit),))
        except Exception:
            return []
        return [dict(r) for r in rows]
